naming:
  FunctionNaming:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false

complexity:
  LongMethod:
    active: false
  TooManyFunctions:
    active: false
